Rename branch

diff --git a/.github/workflows/sync.yaml b/.github/workflows/sync.yaml
--- a/.github/workflows/sync.yaml
+++ b/.github/workflows/sync.yaml
@@ -34,8 +34,8 @@ jobs:
       # Rebase the main branch with upstream
       - name: Rebase upstream changes onto downstream
         run: |
-          git checkout main
-          git rebase upstream/main || (git rebase --abort && echo "Rebase failed, skipping.")
+          git checkout master
+          git rebase upstream/master || (git rebase --abort && echo "Rebase failed, skipping.")
 
       # Check for merge conflicts
       - name: Resolve conflicts (if any)
@@ -49,7 +49,7 @@ jobs:
       # Push changes to downstream repository
       - name: Push changes to downstream repository
         run: |
-          git push origin main || (echo "Push failed. Check for conflicts or permissions." && exit 1)
+          git push origin master || (echo "Push failed. Check for conflicts or permissions." && exit 1)
 
       # Keep the workflow alive
       - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
